"""Added Website Column

Revision ID: 1fd13a5cb0d4
Revises: cd0e928de193
Create Date: 2020-09-26 12:43:49.087745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd13a5cb0d4'
down_revision = 'cd0e928de193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('venue', sa.Column('website', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'website')
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
