"""Not null containt seeking_talent

Revision ID: 60efb97210ce
Revises: 7d41e457587f
Create Date: 2020-09-14 16:11:10.962991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60efb97210ce'
down_revision = '7d41e457587f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'seeking_talent',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
